import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PokemonCard from '../components/PokemonCard'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeData</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main>
        <center>
          <h1 className={styles.title}>PokeData</h1>
          <h2>A WebApp Showcasing Stats of Various Pokemons</h2>
          <PokemonCard name="Bulbasaur" image="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png" type="Grass" description="Bulbasaur can be seen nearer than you might think. It is important for this Pokémon to hide that it is a plant Pokémon in order to remain undetected by kinds of Pokémon like Charmander." stats={{ hp: 45, attack: 49, defense: 49, speed: 45 }} />
        </center>
      </main>
    </div>
  )
}
