import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeData</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main>
        <center>
          <h1 className={styles.title}>PokeData</h1>
          <h2>A WebApp Showcasing Stats of Various Pokemons</h2>
        </center>
      </main>
    </div>
  )
}
